# Generated by Django 5.2.11 on 2026-02-15 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_active', models.BooleanField(default=True)),
                ('max_winners', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Game State',
                'verbose_name_plural': 'Game State',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('position', models.IntegerField(help_text='Grid position 0-24 (left-to-right, top-to-bottom).', unique=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_type', models.CharField(choices=[('row', 'Row'), ('column', 'Column'), ('diagonal', 'Diagonal'), ('full', 'Full Board')], max_length=10)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='game.player')),
            ],
            options={
                'ordering': ['won_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_made', to='game.player')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_received', to='game.player')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='game.task')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('scanner', 'task')},
            },
        ),
    ]
