# Generated by Django 5.2.11 on 2026-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='allow_duplicate_scans',
            field=models.BooleanField(default=False, help_text='Allow a player to scan the same person more than once (for different tasks).'),
        ),
    ]
