# Generated by Django 5.2.11 on 2026-02-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='max_winners',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='winner',
            name='win_type',
            field=models.CharField(choices=[('row', 'Row'), ('column', 'Column'), ('diagonal', 'Diagonal'), ('full', 'Full Board')], max_length=10),
        ),
    ]
